=== RajaDReactiveWorks/test_git/roi-framework/src/main/resources/dynastore.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="DynastoreConfigurations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DynastoreConfiguration" minOccurs="1"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="DynastoreName" minOccurs="1"
								maxOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="version"
												use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="DynastoreInitializer" minOccurs="0"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CustomBuilder" minOccurs="0"
											maxOccurs="1" >
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="builder"
														minOccurs="1" maxOccurs="1" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="SQLBuilder" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SQLQuery" minOccurs="1"
														maxOccurs="1">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="mappedClass"
																		use="required" />
																	<xs:attribute type="xs:string" name="uniqueColumn"
																		use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="InlineBuilder" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="type"
															use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:boolean" name="required"
										use="required" />
									<xs:attribute type="DynastoreInitializerType"
										name="type" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="AccessScope" minOccurs="0"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Getter" minOccurs="1" maxOccurs="1">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Feature" />
													<xs:enumeration value="FeatureGroup" />
													<xs:enumeration value="Site" />
													<xs:minLength value="1" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="PublishEvent" minOccurs="1"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="onReload"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="onTermination"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="onEntryAdded"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="onEntryDeleted"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="onEntryUpdated"
											minOccurs="0" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:boolean" name="isEnabled" use="required" />
					</xs:complexType>
					<!-- Unique ID -->
					<xs:unique name="unique-DynastoreName-version">
						<xs:selector xpath="DynastoreName" />
						<xs:field xpath="@version" />
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Only CUSTOM or SQL or INLINE can be given as type of DynastoreInitializer -->
	<xs:simpleType name="DynastoreInitializerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CUSTOM" />
			<xs:enumeration value="SQL" />
			<xs:enumeration value="INLINE" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== RajaDReactiveWorks/test_git/leap-framework/src/main/resources/dynastore.xml
<?xml version="1.0" encoding="UTF-8"?>
<DynastoreConfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dynastore.xsd">
    <DynastoreConfiguration  isEnabled="true"><!-- isEnabled mandatory from True and false -->
        <DynastoreName version="v1">PicArea</DynastoreName><!-- Name and version are mandatory and of type string-->
       
        
        <DynastoreInitializer required="false" type="CUSTOM" > <!-- Not Mandatory for no Initialization -->
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.PICAddressBuilder</builder>
			</CustomBuilder>
		</DynastoreInitializer>
		
        
        <AccessScope> <!-- Non Mandatory, is not given Feature is default -->
            <Getter>Feature</Getter> <!--Access Scope can be Feature|FeatureGroup|Site. -->
        </AccessScope>
        <PublishEvent><!-- Only eventId are listed and Event description,dispatcher Chanel,Transformation is given in Eventing.xml, Mandatory-->
            <onReload></onReload> <!-- Non Mandatory -->
            <onTermination></onTermination><!-- Non Mandatory -->
            <onEntryAdded></onEntryAdded><!-- Non Mandatory -->
            <onEntryDeleted></onEntryDeleted><!-- Non Mandatory -->
            <onEntryUpdated></onEntryUpdated><!-- Non Mandatory -->
        </PublishEvent>
    </DynastoreConfiguration>
</DynastoreConfigurations>

=== RajaDReactiveWorks/test_git/roi-framework/src/test/resources/TEST-dynastore.xml
<?xml version="1.0" encoding="UTF-8"?>
<DynastoreConfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="dynastore.xsd">
    <!-- Custom Initializer -->
    <DynastoreConfiguration  isEnabled="true"><!-- isEnabled mandatory from True and false -->
        <DynastoreName version="1.0">PicArea</DynastoreName><!-- Name and version are mandatory and of type string-->
       
        <DynastoreInitializer required="true" type="CUSTOM" > <!-- Not Mandatory for no Initialization -->
			<CustomBuilder>
				<builder>com.getusroi.pic.dynastore.DynaPicAddressCustomBuilder</builder>
			</CustomBuilder>
		</DynastoreInitializer>
        
        <AccessScope> <!-- Non Mandatory, is not given Feature is default -->
            <Getter>Feature</Getter> <!--Access Scope can be Feature|FeatureGroup|Site. -->
        </AccessScope>
        <PublishEvent><!-- Only eventId are listed and Event description,dispatcher Chanel,Transformation is given in Eventing.xml, Mandatory-->
            <onReload></onReload> <!-- Non Mandatory -->
            <onTermination>PicAreaOntermination</onTermination><!-- Non Mandatory -->
            <onEntryAdded>PicAreaAdded</onEntryAdded><!-- Non Mandatory -->
            <onEntryDeleted>PicAreaAdded</onEntryDeleted><!-- Non Mandatory -->
            <onEntryUpdated>PicAreaAdded</onEntryUpdated><!-- Non Mandatory -->
        </PublishEvent>
    </DynastoreConfiguration>
    
	<!-- No Initializer is Enabled False-->    
     <DynastoreConfiguration  isEnabled="false"><!-- isEnabled mandatory from True and false -->
        <DynastoreName version="1.0">PicAreaTwo</DynastoreName><!-- Name and version are mandatory and of type string-->
       
        <AccessScope> <!-- Non Mandatory, is not given Feature is default -->
            <Getter>Feature</Getter> <!--Access Scope can be Feature|FeatureGroup|Site. -->
        </AccessScope>
        <PublishEvent><!-- Only eventId are listed and Event description,dispatcher Chanel,Transformation is given in Eventing.xml, Mandatory-->
            <onReload></onReload> <!-- Non Mandatory -->
            <onTermination>PicAreaOntermination</onTermination><!-- Non Mandatory -->
            <onEntryAdded>PicAreaAdded</onEntryAdded><!-- Non Mandatory -->
            <onEntryDeleted></onEntryDeleted><!-- Non Mandatory -->
            <onEntryUpdated></onEntryUpdated><!-- Non Mandatory -->
        </PublishEvent>
    </DynastoreConfiguration>
    
    <!-- No Initializer-->    
     <DynastoreConfiguration  isEnabled="true"><!-- isEnabled mandatory from True and false -->
        <DynastoreName version="1.0">PicArea_NoInitializer</DynastoreName><!-- Name and version are mandatory and of type string-->
       
        <AccessScope> <!-- Non Mandatory, is not given Feature is default -->
            <Getter>Feature</Getter> <!--Access Scope can be Feature|FeatureGroup|Site. -->
        </AccessScope>
        <PublishEvent><!-- Only eventId are listed and Event description,dispatcher Chanel,Transformation is given in Eventing.xml, Mandatory-->
            <onReload></onReload> <!-- Non Mandatory -->
            <onTermination>PicAreaOntermination</onTermination><!-- Non Mandatory -->
            <onEntryAdded>PicAreaAdded</onEntryAdded><!-- Non Mandatory -->
            <onEntryDeleted></onEntryDeleted><!-- Non Mandatory -->
            <onEntryUpdated></onEntryUpdated><!-- Non Mandatory -->
        </PublishEvent>
    </DynastoreConfiguration>
    
    <!-- Test SQL-List of Mapper -->
    <DynastoreConfiguration  isEnabled="true"><!-- isEnabled mandatory from True and false -->
        <DynastoreName version="1.0">PicAreaSQL-List-OF-Mapper</DynastoreName><!-- Name and version are mandatory and of type string-->
      
        <DynastoreInitializer required="true" type="SQL" > <!-- Not Mandatory for no Initialization -->
			<SQLBuilder>
				<SQLQuery mappedClass="Map-Of-Map" uniqueColumn="AreaId">select * from AreaList where AreaType='Stage'</SQLQuery>
			</SQLBuilder>
		</DynastoreInitializer>
        <AccessScope> <!-- Non Mandatory, is not given Feature is default -->
            <Getter>Feature</Getter> <!--Access Scope can be Feature|FeatureGroup|Site. -->
        </AccessScope>
        <PublishEvent><!-- Only eventId are listed and Event description,dispatcher Chanel,Transformation is given in Eventing.xml, Mandatory-->
            <onReload></onReload> <!-- Non Mandatory -->
            <onTermination>PicAreaOntermination</onTermination><!-- Non Mandatory -->
            <onEntryAdded>PicAreaAdded</onEntryAdded><!-- Non Mandatory -->
            <onEntryDeleted></onEntryDeleted><!-- Non Mandatory -->
            <onEntryUpdated></onEntryUpdated><!-- Non Mandatory -->
        </PublishEvent>
    </DynastoreConfiguration>
    <!-- Test SQL-custom Mapper-->
    <DynastoreConfiguration  isEnabled="true"><!-- isEnabled mandatory from True and false -->
        <DynastoreName version="1.0">PicAreaSQL-Custom-Mapper</DynastoreName><!-- Name and version are mandatory and of type string-->
       
        <DynastoreInitializer required="true" type="SQL" > <!-- Not Mandatory for no Initialization -->
			<SQLBuilder>
				<SQLQuery mappedClass="com.getusroi.pic.dynastore.PicAddressMapper" uniqueColumn="">select * from AreaList where AreaType='Stage'</SQLQuery>
			</SQLBuilder>
		</DynastoreInitializer>
        <AccessScope> <!-- Non Mandatory, is not given Feature is default -->
            <Getter>Feature</Getter> <!--Access Scope can be Feature|FeatureGroup|Site. -->
        </AccessScope>
        <PublishEvent><!-- Only eventId are listed and Event description,dispatcher Chanel,Transformation is given in Eventing.xml, Mandatory-->
            <onReload></onReload> <!-- Non Mandatory -->
            <onTermination>PicAreaOntermination</onTermination><!-- Non Mandatory -->
            <onEntryAdded>PicAreaAdded</onEntryAdded><!-- Non Mandatory -->
            <onEntryDeleted></onEntryDeleted><!-- Non Mandatory -->
            <onEntryUpdated></onEntryUpdated><!-- Non Mandatory -->
        </PublishEvent>
    </DynastoreConfiguration>
    <!-- Dynastore initializer INLINE JSON TO mAP -->
    <DynastoreConfiguration  isEnabled="true"><!-- isEnabled mandatory from True and false -->
        <DynastoreName version="1.0">PicArea-INLINE-json</DynastoreName><!-- Name and version are mandatory and of type string-->
       
        <DynastoreInitializer required="true" type="INLINE" > <!-- Not Mandatory for no Initialization -->
			<InlineBuilder type="JSON-TO-Map">
				{"variable" :"lodnum","locale_id":"US_ENGLISH"}
			</InlineBuilder>
		</DynastoreInitializer>
        <AccessScope> <!-- Non Mandatory, is not given Feature is default -->
            <Getter>Feature</Getter> <!--Access Scope can be Feature|FeatureGroup|Site. -->
        </AccessScope>
        <PublishEvent><!-- Only eventId are listed and Event description,dispatcher Chanel,Transformation is given in Eventing.xml, Mandatory-->
            <onReload></onReload> <!-- Non Mandatory -->
            <onTermination>PicAreaOntermination</onTermination><!-- Non Mandatory -->
            <onEntryAdded>PicAreaAdded</onEntryAdded><!-- Non Mandatory -->
            <onEntryDeleted></onEntryDeleted><!-- Non Mandatory -->
            <onEntryUpdated></onEntryUpdated><!-- Non Mandatory -->
        </PublishEvent>
    </DynastoreConfiguration>
</DynastoreConfigurations>
