=== RajaDReactiveWorks/test_git/roi-framework/src/main/resources/permastoreconfig.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="PermaStoreConfigurations">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PermaStoreConfiguration" maxOccurs="unbounded"
					minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" minOccurs="1" maxOccurs="1"
								nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="isEnabled" minOccurs="1" maxOccurs="1"
								nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:boolean"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="isGlobal" minOccurs="0" maxOccurs="1"
								nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:boolean"/>
								</xs:simpleType>
							</xs:element>
						
							<xs:element name="featureInfo" minOccurs="1"
								maxOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="featureName"
												use="optional" />
											<xs:attribute type="xs:string" name="featureGroup"
												use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="DataType" minOccurs="1" maxOccurs="1"
								nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ConfigurationBuilder" minOccurs="1"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CustomBuilder" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="builder"
														minOccurs="1" maxOccurs="1" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="SQLBuilder" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="SQLQuery" minOccurs="1"
														maxOccurs="1">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="mappedClass"
																		use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="InlineBuilder" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="type"
															use="required" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="ConfigurationBuilderType"
										name="type" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="PublishPermaStoreEvent" minOccurs="0"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="OnConfigDelete"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="OnConfigStatusChange"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="OnConfigEntryDelete"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="OnConfigEntryAdd"
											minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="OnConfigEntryUpdate"
											minOccurs="0" maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="SubscribePermaStoreEvents"
								minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PermaStoreEvent" minOccurs="1"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="EventName"
														minOccurs="1" maxOccurs="1" />
													<xs:element type="xs:string" name="PermaStoreEventHandler"
														minOccurs="0" maxOccurs="1" />
												</xs:sequence>
												<xs:attribute type="event" name="onEvent" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Only reload or customHandler can be given to onEvent of PermaStoreEvent -->
	<xs:simpleType name="event">
		<xs:restriction base="xs:string">
			<xs:enumeration value="reload" />
			<xs:enumeration value="customHandler" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Only CUSTOM or SQL or INLINE can be given as type of ConfigurationBuilder -->
	<xs:simpleType name="ConfigurationBuilderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CUSTOM" />
			<xs:enumeration value="SQL" />
			<xs:enumeration value="INLINE" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== RajaDReactiveWorks/test_git/leap-framework/src/test/resources/Test-PermaStoreConfig-forPolicy.xml
<?xml version="1.0" encoding="UTF-8"?>
<PermaStoreConfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="permastoreconfig.xsd">
	<!-- Test Custom PermaStoreBuilder -->
	<PermaStoreConfiguration>
		<Name>GetStagingAreas</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1"/>
		<DataType>List</DataType>
		<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.StageingAreaListBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents> 
			<PermaStoreEvent onEvent="reload">
			     <EventName>xyz</EventName>
			     <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	<!-- Test INLINE JSON-MAP builder -->
	<PermaStoreConfiguration>
        <Name>loadnum</Name>
        <isEnabled>true</isEnabled>
        
        <featureInfo featureName="feature1" featureGroup="featuregroup1"/>
        <DataType>Map</DataType>
        <ConfigurationBuilder type="INLINE">
            <InlineBuilder type="JSON-TO-Map">
                {"variable" :"lodnum","locale_id":"US_ENGLISH"}
            </InlineBuilder>
        </ConfigurationBuilder>
        <PublishPermaStoreEvent>
            <OnConfigDelete></OnConfigDelete>
            <OnConfigStatusChange></OnConfigStatusChange>
            <OnConfigEntryDelete></OnConfigEntryDelete>
            <OnConfigEntryAdd></OnConfigEntryAdd>
            <OnConfigEntryUpdate></OnConfigEntryUpdate>
        </PublishPermaStoreEvent>
        <SubscribePermaStoreEvents>
            <PermaStoreEvent onEvent="reload">
            <EventName>TerminologyChange</EventName>
                 <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
            </PermaStoreEvent>
        </SubscribePermaStoreEvents>
    </PermaStoreConfiguration>
  	<PermaStoreConfiguration>
		<Name>GetStagingAreasOne</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1"/>
		<DataType>List</DataType>
		<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.StageingAreaStringBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents> 
			<PermaStoreEvent onEvent="reload">
			     <EventName>xyz</EventName>
			     <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	
</PermaStoreConfigurations>

=== RajaDReactiveWorks/test_git/Integration/Integration-service-implementation/src/main/resources/Integration-permastore.xml
<?xml version="1.0" encoding="UTF-8"?>
<PermaStoreConfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="permastoreconfig.xsd">

	<PermaStoreConfiguration>
		<Name>EntityTypeStrategy</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="ALPSIntegration" featureGroup="PAndG" />
		<DataType>Map</DataType>
		<ConfigurationBuilder type="INLINE">
			<InlineBuilder type="JSON-TO-Map">
				{
				"config1": {
				"EntityTypeStrategy": "json-key",
				"JSONRootKey": "order",
				"apply": {
				"Entity": "order",
				"FileContentSpliting": {
				"splitingRequired": true,
				"JSONPath": "//order"
				},
				"validation": {
				"validationRequired": false,
				"validationXSD":
				"some/some/Orders.xsd"
				},
				"aggregationOREnrichment": {
				"aggregationRequired": true,
				"ImplRoute": "EnrichImp"
				},
				"transformation": {
				"transformationXSLT": "all//all//Unprocessed//productxslt.xslt"
				}
				}
				},
				"confing2": {
				"EntityTypeStrategy": "XML-Root",
				"XMLRootTag": "products",
				"apply": {
				"Entity": "products",
				"FileContentSpliting": {
				"splitingRequired": false,
				"XPath": "products/product"
				},
				"validation": {
				"validationRequired": false,
				"validationXSD":
				"some/some/Orders.xsd"
				},
				"aggregationOREnrichment": {
				"aggregationRequired": true,
				"ImplRoute": "EnrichImp"
				},
				"transformation": {
				"transformationXSLT": "all//all//Unprocessed//productxslt.xslt"
				}
				}
				},
				"confing3": {
				"EntityTypeStrategy": "CSV-Header",
				"CSVHeaderContains":"productId",
				"apply": {
				"Entity": "productsDetails",
				"FileContentSpliting": {
				"splitingRequired": true,
				},
				"validation": {
				"validationRequired": false,
				"validationXSD":
				"some/some/Orders.xsd"
				},
				"aggregationOREnrichment": {
				"aggregationRequired": true,
				"ImplRoute": "EnrichImp"
				},
				"transformation": {
				"transformationXSLT": "all//all//Unprocessed//productxslt.xslt"
				}
				}
				},
				"confing4": {
				"EntityTypeStrategy": "json-array-key",
				"JSONRootKey":"orderId",
				"apply": {
				"Entity": "order",
				"FileContentSpliting": {
				"splitingRequired": true,
				},
				"validation": {
				"validationRequired": false,
				"validationXSD":
				"some/some/Orders.xsd"
				},
				"aggregationOREnrichment": {
				"aggregationRequired": true,
				"ImplRoute": "EnrichImp"
				},
				"transformation": {
				"transformationXSLT": "all//all//Unprocessed//productxslt.xslt"
				}
				}
				},
				"config5": {
				"EntityTypeStrategy": "json-key",
				"JSONRootKey": "orders",
				"apply": {
				"Entity": "orders",
				"FileContentSpliting": {
				"splitingRequired": true,
				"JSONPath": "orders/order"
				},
				"validation": {
				"validationRequired": false,
				"validationXSD":
				"some/some/Orders.xsd"
				},
				"aggregationOREnrichment": {
				"aggregationRequired": true,
				"ImplRoute": "EnrichImp"
				},
				"transformation": {
				"transformationXSLT": "all//all//Unprocessed//productxslt.xslt"
				}
				}
				}
				}
			</InlineBuilder>
		</ConfigurationBuilder>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>xyz</EventName>
				<PermaStoreEventHandler>com.getusroi.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
</PermaStoreConfigurations>

=== RajaDReactiveWorks/test_git/leap-framework/src/main/resources/PermaStoreConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<PermaStoreConfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="permastoreconfig.xsd">
	<PermaStoreConfiguration>
		<Name>AreaList</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1"/>
		<DataType>List</DataType>
		<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.PICAddressBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents> 
			<PermaStoreEvent onEvent="reload">
			     <EventName>xyz</EventName>
			     <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>

	<!--  
	<PermaStoreConfiguration>
		<Name>PicAreaList</Name>
		<featureInfo featureGroup="" featureName=""/>
		<DataType>List</DataType>
		<ConfigurationBuilder type="SQL">
			<SQLBuilder>
				<SQLQuery mappedClass="com.attunedlabs.pic.Area">select * from table where areaType=?</SQLQuery>
			</SQLBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete></OnConfigDelete>
			<OnConfigStatusChange></OnConfigStatusChange>
			<OnConfigEntryDelete></OnConfigEntryDelete>
			<OnConfigEntryAdd></OnConfigEntryAdd>
			<OnConfigEntryUpdate></OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
			<EventName>hhj</EventName>
			     <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	 -->
	<PermaStoreConfiguration>
        <Name>lodnum</Name>
        		<isEnabled>true</isEnabled>
        
        <featureInfo featureName="feature1" featureGroup="featuregroup1"/>
        <DataType>Map</DataType>
        <ConfigurationBuilder type="INLINE">
            <InlineBuilder type="JSON-TO-Map">
                {"variable" :"lodnum","locale_id":"US_ENGLISH"}
            </InlineBuilder>
        </ConfigurationBuilder>
        <PublishPermaStoreEvent>
            <OnConfigDelete></OnConfigDelete>
            <OnConfigStatusChange></OnConfigStatusChange>
            <OnConfigEntryDelete></OnConfigEntryDelete>
            <OnConfigEntryAdd></OnConfigEntryAdd>
            <OnConfigEntryUpdate></OnConfigEntryUpdate>
        </PublishPermaStoreEvent>
        <SubscribePermaStoreEvents>
            <PermaStoreEvent onEvent="reload">
            <EventName>TerminologyChange</EventName>
                 <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
            </PermaStoreEvent>
        </SubscribePermaStoreEvents>
    </PermaStoreConfiguration>
    
    	<PermaStoreConfiguration>
		<Name>AreaListSecond</Name>
		<isEnabled>false</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1"/>
		    <DataType>Map</DataType>
      	<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.PICAddressBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents> 
			<PermaStoreEvent onEvent="reload">
			     <EventName>xyz</EventName>
			     <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	
	<PermaStoreConfiguration>
        <Name>GetStagingAreas</Name>
        		<isEnabled>true</isEnabled>
        
        <featureInfo featureName="feature1" featureGroup="featuregroup1"/>
        <DataType>Map</DataType>
        <ConfigurationBuilder type="INLINE">
            <InlineBuilder type="JSON-TO-Map">
                {"variable" :"lodnum","locale_id":"US_ENGLISH"}
            </InlineBuilder>
        </ConfigurationBuilder>
        <PublishPermaStoreEvent>
            <OnConfigDelete></OnConfigDelete>
            <OnConfigStatusChange></OnConfigStatusChange>
            <OnConfigEntryDelete></OnConfigEntryDelete>
            <OnConfigEntryAdd></OnConfigEntryAdd>
            <OnConfigEntryUpdate></OnConfigEntryUpdate>
        </PublishPermaStoreEvent>
        <SubscribePermaStoreEvents>
            <PermaStoreEvent onEvent="reload">
            <EventName>TerminologyChange</EventName>
                 <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
            </PermaStoreEvent>
        </SubscribePermaStoreEvents>
    </PermaStoreConfiguration>
  	<PermaStoreConfiguration>
		<Name>AreaList</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1"/>
		<DataType>List</DataType>
		<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.PICAddressBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents> 
			<PermaStoreEvent onEvent="reload">
			     <EventName>xyz</EventName>
			     <PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
  
</PermaStoreConfigurations>

=== RajaDReactiveWorks/test_git/roi-framework/src/test/resources/BadPermaStoreConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<PermaStoreConfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="permastoreconfig.xsd">
	<PermaStoreConfiguration>
		<!--  <Name>AreaList</Name>-->
		<featureInfo featureName="" featureGroup=""/>
		<DataType>List</DataType>
		<ConfigurationBuilder>
			<CustomBuilder>
				<builder>com.getusroi.configBuilder.PICAdressBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents> 
			<PermaStoreEvent onEvent="reload">
			     <EventName>xyz</EventName>
			     <PermaStoreEventHandler>com.getusroi.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	
	<PermaStoreConfiguration>
		<Name>PicAreaList</Name>
		<featureInfo featureGroup="fgf" featureName=""/>
		<DataType>List</DataType>
		<ConfigurationBuilder>
			<SQLBuilder>
				<SQLQuery mappedClass="com.getusroi.pic.Area">select * from table where areaType=?</SQLQuery>
			</SQLBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete></OnConfigDelete>
			<OnConfigStatusChange></OnConfigStatusChange>
			<OnConfigEntryDelete></OnConfigEntryDelete>
			<OnConfigEntryAdd></OnConfigEntryAdd>
			<OnConfigEntryUpdate></OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
			<EventName>hhj</EventName>
			     <PermaStoreEventHandler>com.getusroi.inventory.HandlePicAddressAddition</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
</PermaStoreConfigurations>

=== RajaDReactiveWorks/test_git/leap-framework/src/test/resources/PermaStoreConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<PermaStoreConfigurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="permastoreconfig.xsd">
	<PermaStoreConfiguration>
		<Name>AreaList</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>List</DataType>
		<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.PICAddressBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent
			</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>xyz</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>

	<!-- Test SQLBuilder with Custom Mapper-->
	<PermaStoreConfiguration>
		<Name>TestSQLBuilderCustomMapper</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>List</DataType>
		<ConfigurationBuilder type="SQL">
			<SQLBuilder>
				<SQLQuery mappedClass="com.attunedlabs.permastore.config.StageAreaPSSQLResultsetMapper">select * from AreaList where AreaType='Stage'
				</SQLQuery>
			</SQLBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete></OnConfigDelete>
			<OnConfigStatusChange></OnConfigStatusChange>
			<OnConfigEntryDelete></OnConfigEntryDelete>
			<OnConfigEntryAdd></OnConfigEntryAdd>
			<OnConfigEntryUpdate></OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>hhj</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	<!-- Test SQLBuilder with List-OF-Map builder-->
	<PermaStoreConfiguration>
		<Name>TestSQLBuilderList-OF-MapMapper</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>List</DataType>
		<ConfigurationBuilder type="SQL">
			<SQLBuilder>
				<SQLQuery mappedClass="List-Of-Map">select * from AreaList where AreaType='Stage'
			</SQLQuery>
			</SQLBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete></OnConfigDelete>
			<OnConfigStatusChange></OnConfigStatusChange>
			<OnConfigEntryDelete></OnConfigEntryDelete>
			<OnConfigEntryAdd></OnConfigEntryAdd>
			<OnConfigEntryUpdate></OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>hhj</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	
	<PermaStoreConfiguration>
		<Name>lodnum</Name>
		<isEnabled>true</isEnabled>

		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>Map</DataType>
		<ConfigurationBuilder type="INLINE">
			<InlineBuilder type="JSON-TO-Map">
				{"variable" :"lodnum","locale_id":"US_ENGLISH"}
			</InlineBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete></OnConfigDelete>
			<OnConfigStatusChange></OnConfigStatusChange>
			<OnConfigEntryDelete></OnConfigEntryDelete>
			<OnConfigEntryAdd></OnConfigEntryAdd>
			<OnConfigEntryUpdate></OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>TerminologyChange</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>

	<PermaStoreConfiguration>
		<Name>AreaListSecond</Name>
		<isEnabled>false</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>Map</DataType>
		<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.PICAddressBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent
			</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>xyz</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
	<PermaStoreConfiguration>
		<Name>AreaListThree</Name>
		<isEnabled>false</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>Map</DataType>
		<ConfigurationBuilder type="CUSTOM">
			<CustomBuilder>
				<builder>com.attunedlabs.permastore.config.PICAddressBuilder</builder>
			</CustomBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete>AreaListDeletedEvent</OnConfigDelete>
			<OnConfigStatusChange>AreaListStatusChangedEvent
			</OnConfigStatusChange>
			<OnConfigEntryDelete>AreaDeletedEvent</OnConfigEntryDelete>
			<OnConfigEntryAdd>AreaAddedEvent</OnConfigEntryAdd>
			<OnConfigEntryUpdate>AreaUpdatedEvent</OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>xyz</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>

	<PermaStoreConfiguration>
		<Name>lodnumSecond</Name>
		<isEnabled>false</isEnabled>

		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>Map</DataType>
		<ConfigurationBuilder type="INLINE">
			<InlineBuilder type="JSON-TO-Map">
				{"variable" :"lodnum","locale_id":"US_ENGLISH"}
			</InlineBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete></OnConfigDelete>
			<OnConfigStatusChange></OnConfigStatusChange>
			<OnConfigEntryDelete></OnConfigEntryDelete>
			<OnConfigEntryAdd></OnConfigEntryAdd>
			<OnConfigEntryUpdate></OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>TerminologyChange</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
<!-- 	For Camel Route Builder
	<PermaStoreConfiguration>
		<Name>camelRoute</Name>
		<isEnabled>true</isEnabled>
		<featureInfo featureName="feature1" featureGroup="featuregroup1" />
		<DataType>JSON</DataType>
		<ConfigurationBuilder type="CAMEL-ROUTE">
			<CamelRouteBuilder>
				<routeName>loadAreaList</routeName>
			</CamelRouteBuilder>
		</ConfigurationBuilder>
		<PublishPermaStoreEvent>
			<OnConfigDelete></OnConfigDelete>
			<OnConfigStatusChange></OnConfigStatusChange>
			<OnConfigEntryDelete></OnConfigEntryDelete>
			<OnConfigEntryAdd></OnConfigEntryAdd>
			<OnConfigEntryUpdate></OnConfigEntryUpdate>
		</PublishPermaStoreEvent>
		<SubscribePermaStoreEvents>
			<PermaStoreEvent onEvent="reload">
				<EventName>TerminologyChange</EventName>
				<PermaStoreEventHandler>com.attunedlabs.inventory.HandlePicAddressAddition
				</PermaStoreEventHandler>
			</PermaStoreEvent>
		</SubscribePermaStoreEvents>
	</PermaStoreConfiguration>
 -->
</PermaStoreConfigurations>
