=== RajaDReactiveWorks/test_git/leap-framework/src/test/resources/integration-fwk-pipeline.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:fwk="http://attunedlabs.com/internal/integration-fwk-Supporting">
	<xs:import schemaLocation="integration-fwk-Supporting.xsd"
		namespace="http://attunedlabs.com/internal/integration-fwk-Supporting" />

	<xs:element name="IntegrationPipes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="IntegrationPipe" maxOccurs="unbounded"
					minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PipeActivity" maxOccurs="unbounded"
								minOccurs="0">
								<xs:complexType>
									<xs:all>
										<xs:element name="XSLTEnricherActivity" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="xsltpathMapper" maxOccurs="1"
														minOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="xsltPathMap" maxOccurs="unbounded"
																	minOccurs="1">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="filePath" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
											</xs:complexType>
										</xs:element>
										<xs:element name="FTLEnricherActivity" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ftlpathMapper" maxOccurs="1"
														minOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="ftlPathMap" maxOccurs="unbounded"
																	minOccurs="1">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="filePath" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
																<xs:element name="ftlMapto" maxOccurs="1"
																	minOccurs="1">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="toXpath"
																					use="required" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="ftlDataMapper">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="ftlfieldMapper" maxOccurs="unbounded"
																	minOccurs="0">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="msgXpath"
																					use="required" />
																				<xs:attribute type="xs:string" name="ftlField"
																					use="required" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
											</xs:complexType>
										</xs:element>
										<xs:element name="JDBCIntActivity" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="DBConfig" maxOccurs="1"
														minOccurs="1">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="operation"
																		use="required" />
																	<xs:attribute name="dbType" use="required">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="MYSQL" />
																				<xs:enumeration value="CASSANDRA" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element type="xs:string" name="SQL" />
													<xs:element name="dbmsMapper">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="fieldMapper" maxOccurs="unbounded"
																	minOccurs="1">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="xPath"
																					use="required" />
																				<xs:attribute type="xs:string" name="Field"
																					use="required" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="RowMapper" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="xmlFieldMapper" maxOccurs="unbounded"
																	minOccurs="0">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="xpath"
																					use="optional" />
																				<xs:attribute type="xs:string" name="columnKey"
																					use="optional" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
											</xs:complexType>
										</xs:element>
										<xs:element name="EmailNotifyActivity" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="EmailNotification">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="MailAttachments" minOccurs="0"
																	maxOccurs="1">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="MailAttachment">
																				<xs:complexType>
																					<xs:simpleContent>
																						<xs:extension base="xs:string">
																							<xs:attribute type="xs:string"
																								name="mailAttachmentXpath" />
																							<xs:attribute type="xs:string"
																								name="mailAttachmentNameXpath" />
																							<xs:attribute type="xs:string"
																								name="mailAttachmentFormatXpath" />
																						</xs:extension>
																					</xs:simpleContent>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute type="xs:string" name="recepientIdXpath" />
															<xs:attribute type="xs:string" name="mailSubjectXpath" />
															<xs:attribute type="xs:string" name="mailBodyXpath" />
															<xs:attribute type="xs:string" name="hasAttachments" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
											</xs:complexType>
										</xs:element>
										<xs:element name="FilterPipelineActivity"
											minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="conditions">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="condition" minOccurs="1"
																	maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="expression" type="xs:string"
																			use="required"></xs:attribute>
																		<xs:attribute name="value" type="xs:string"
																			use="required"></xs:attribute>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="operator" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:enumeration value="AND" />
																		<xs:enumeration value="OR" />
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
													<xs:element name="conditionSuccess" maxOccurs="1"
														minOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element ref="fwk:send" minOccurs="0"
																	maxOccurs="1" />
																<xs:element ref="fwk:drop" minOccurs="0"
																	maxOccurs="1" />
																<xs:element ref="fwk:filterResponse" minOccurs="0"
																	maxOccurs="1" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="conditionFaliure" minOccurs="0"
														maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element ref="fwk:send" minOccurs="0"
																	maxOccurs="1" />
																<xs:element ref="fwk:drop" minOccurs="0"
																	maxOccurs="1" />
																<xs:element ref="fwk:filterResponse" minOccurs="0"
																	maxOccurs="1" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string"></xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="CamelRouteEndPoint" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CamelRoute" minOccurs="1"
														maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="FeatureContext" minOccurs="0"
																	maxOccurs="1">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="FeatureGroup" />
																				<xs:attribute type="xs:string" name="FeatureName" />
																				<xs:attribute type="xs:string" name="VendorName" />
																				<xs:attribute type="xs:string" name="Version" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
																<xs:element type="xs:string" name="ServiceName"
																	minOccurs="1" maxOccurs="1" />
																<xs:element type="xs:string" name="ExecutionRoute"
																	minOccurs="1" maxOccurs="1" />
															</xs:sequence>
															<xs:attribute type="xs:boolean" name="isSameFeature" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
											</xs:complexType>
										</xs:element>
										<xs:element name="PropertiesActivity" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="PropertiesMapping" minOccurs="1"
														maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="setToXpath"
																		use="required" />
																	<xs:attribute type="xs:string" name="elementToAdd"
																		use="required" />
																	<xs:attribute type="xs:string" name="propertyValue"
																		use="required" />
																	<xs:attribute name="propertyValueSource"
																		use="required">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="Direct" />
																				<xs:enumeration value="LeapHeader" />
																				<xs:enumeration value="Exchange" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="name" />
											</xs:complexType>
										</xs:element>
										<xs:element name="EventPublishActivity" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="EventActivityParams">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="EventData" maxOccurs="unbounded"
																		minOccurs="0">
																		<xs:complexType>
																			<xs:simpleContent>
																				<xs:extension base="xs:string">
																					<xs:attribute type="xs:string" name="xpathExpression" use="required" />
																					<xs:attribute type="xs:string" name="ExpressionValue" use="optional" />
																				</xs:extension>
																			</xs:simpleContent>
																		</xs:complexType>
																</xs:element>
            												</xs:sequence>
         												 </xs:complexType>
        											</xs:element>
     											 </xs:sequence>
      											<xs:attribute type="xs:string" name="EventName"/>
    										</xs:complexType>
 										 </xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" />
						<xs:attribute type="xs:boolean" name="isEnabled" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RajaDReactiveWorks/test_git/leap-framework/src/test/resources/Integration_pipeline.xml
<?xml version="1.0" encoding="UTF-8"?>
<IntegrationPipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="integration-fwk-pipeline.xsd">
	<IntegrationPipe name="SAC-SR" isEnabled="true">
	<PipeActivity>
		<XSLTEnricherActivity name="testxsltTransform">
			<xsltpathMapper>
				<xsltPathMap filePath="testxslt.xsl" />
				<xsltPathMap filePath="testxslt2.xsl" />
			</xsltpathMapper>
		</XSLTEnricherActivity>
		</PipeActivity>
		<PipeActivity>
			<FTLEnricherActivity name="sacFtlTransform">
				<ftlpathMapper>
					<ftlPathMap filePath="sacNotification.ftl" />
					<ftlMapto toXpath="ServiceRequest/RequestDetail/ProblemDescription" />
				</ftlpathMapper>
				<ftlDataMapper>
					<ftlfieldMapper msgXpath="ServiceRequest/RequestDetail/WOPrice"
						ftlField="Price" />
					<ftlfieldMapper msgXpath="ServiceRequest/RequestSource/ServiceRequestId"
						ftlField="Id" />
					<ftlfieldMapper msgXpath="ServiceRequest/RequestDetail/@Status"
						ftlField="Type" />
				</ftlDataMapper>
			</FTLEnricherActivity>
		</PipeActivity>
	</IntegrationPipe>
</IntegrationPipes>

=== RajaDReactiveWorks/test_git/leap-framework/src/test/resources/integration_pipelinev1.xml
<?xml version="1.0" encoding="UTF-8"?>
<IntegrationPipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="integration-fwk-pipeline.xsd">
	<IntegrationPipe name="SAC-SR" isEnabled="true">
		<PipeActivity>
			<XSLTEnricherActivity name="testxsltTransform">
				<xsltpathMapper>
					<xsltPathMap filePath="testxslt.xsl" />
					<xsltPathMap filePath="testxslt2.xsl" />
				</xsltpathMapper>
			</XSLTEnricherActivity>
		</PipeActivity>
		
		<PipeActivity>
			<JDBCIntActivity name="testjdbcInsert">
				<DBConfig operation="INSERT" dbType="MYSQL"/>
				<SQL>INSERT INTO testtable
					(amount,number,description,dateconfigured)
					VALUES (fld3,fld1,fld2,fld4);
				</SQL>
				<dbmsMapper>
					<fieldMapper xPath="intermessage/invoice/amount" Field="fld3" />
					<fieldMapper xPath="intermessage/invoice/description"
						Field="fld2" />
					<fieldMapper xPath="intermessage/invoice/number" Field="fld1" />
					<fieldMapper xPath="intermessage/invoice/dateconfigured"
						Field="fld4" />
				</dbmsMapper>
			</JDBCIntActivity>
		</PipeActivity>
	</IntegrationPipe>
</IntegrationPipes>

=== RajaDReactiveWorks/test_git/leap-framework/src/test/resources/integration_pipelinev3.xml
<?xml version="1.0" encoding="UTF-8"?>
<IntegrationPipes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="integration-fwk-pipeline.xsd"
	xmlns:fwk="http://attunedlabs.com/internal/integration-fwk-Supporting">
	<IntegrationPipe name="SAC-SR" isEnabled="true">
		<PipeActivity>
			<XSLTEnricherActivity name="testxsltTransform1">
				<xsltpathMapper>
					<xsltPathMap filePath="testxslt.xsl" />
					<xsltPathMap filePath="testxslt2.xsl" />
				</xsltpathMapper>
			</XSLTEnricherActivity>
		</PipeActivity>
		<PipeActivity>
			<FTLEnricherActivity name="testftlTransform1">
				<ftlpathMapper>
					<ftlPathMap filePath="paymentNotificationTemplate1.ftl" />
					<ftlMapto toXpath="EmailNotification/Body"/>
				</ftlpathMapper>
				<ftlDataMapper>
					<ftlfieldMapper msgXpath="intermsg/invoice/template/recepientAmount"
						ftlField="recepientAmount" />
					<ftlfieldMapper msgXpath="intermsg/invoice/template/description"
						ftlField="description" />
				</ftlDataMapper>
			</FTLEnricherActivity>
		</PipeActivity>
		<PipeActivity>
		<FTLEnricherActivity name="testftlTransform1">
    <ftlpathMapper>
     <ftlPathMap filePath="ftlBodyTemplate.ftl" />
     <ftlMapto toXpath="EmailNotification/Body" />
    </ftlpathMapper>
    <ftlDataMapper>
     <ftlfieldMapper msgXpath="EmailNotification/Payload/Event/@ID"
      ftlField="serviceID" />
     <ftlfieldMapper msgXpath="EmailNotification/Payload/Event/SRNumber"
      ftlField="SRNumber" />
     <ftlfieldMapper msgXpath="EmailNotification/Payload/Event/SRLocation"
      ftlField="location" />
    </ftlDataMapper>
   </FTLEnricherActivity>
   </PipeActivity>
		<PipeActivity>
		<FilterPipelineActivity name="filterPipeLine">
			<conditions operator="AND">
				<condition expression="DATA2SC/CALL/@TYPE"  value="WoNew"/>
				<condition expression="DATA2SC/@ID"  value="WoNew"/>
			</conditions>
		<conditionSuccess>
          	<fwk:send value="true"/>
     	</conditionSuccess>
     	<conditionFaliure>
		   <fwk:drop value="true"/>
    	</conditionFaliure>
	</FilterPipelineActivity>
		</PipeActivity>
		 <PipeActivity>
			<EmailNotifyActivity name="testemailnotification">
					<EmailNotification recepientIdXpath="EmailNotification/Recipients/Recipient"
					mailSubjectXpath="EmailNotification/Subject" mailBodyXpath="EmailNotification/Body"/>
			</EmailNotifyActivity>
		</PipeActivity> 
		
		<PipeActivity>
			<FTLEnricherActivity name="testftlTransform1">
				<ftlpathMapper>
					<ftlPathMap filePath="paymentNotificationTemplate1.ftl" />
					<ftlMapto toXpath="EmailNotification/Body" />
				</ftlpathMapper>
				<ftlDataMapper>
					<ftlfieldMapper msgXpath="intermsg/invoice/template/recepientAmount"
						ftlField="recepientAmount" />
					<ftlfieldMapper msgXpath="intermsg/invoice/template/description"
						ftlField="description" />
				</ftlDataMapper>
			</FTLEnricherActivity>
		</PipeActivity>
	</IntegrationPipe>
</IntegrationPipes>
