=== RajaDReactiveWorks/test_git/leap-framework/src/main/resources/policies.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="policies">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="policy" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="policyName"
								minOccurs="1" maxOccurs="1" />
							<xs:element name="feature" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="featureGroup"
												use="required" />
											<xs:attribute type="xs:string" name="featureName"
												use="optional" />
											<xs:attribute type="xs:string" name="vendor"
												use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:boolean" name="enabled"
								minOccurs="1" maxOccurs="1" />
							<xs:element name="fact" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="name" minOccurs="1"
											maxOccurs="1" />
										<xs:element type="xs:string" name="type" minOccurs="1"
											maxOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="policyEvaluation" minOccurs="1"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="evaluation" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="expression" minOccurs="1"
														maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="name"
																		use="required" />
																	<xs:attribute type="xs:string" name="expValue"
																		use="required" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element type="xs:string" name="evaluateExp"
														minOccurs="1" maxOccurs="1" />
												</xs:sequence>
												<xs:attribute type="eval" name="evalDialect"
													use="required" />
												<xs:attribute type="xs:int" name="salience"
													use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="policyResponse" minOccurs="1"
								maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="policyDefinedFact" minOccurs="0"
											maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="factDescription" minOccurs="1"
														maxOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="factAttribute" maxOccurs="unbounded"
																	minOccurs="1">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="name"
																					use="required" />
																				<xs:attribute type="xs:string" name="type"
																					use="optional" />
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute type="xs:string" name="type"
																use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="factMapping"
											minOccurs="0" maxOccurs="1" />
									</xs:sequence>
									<xs:attribute type="policyResponseType" name="type" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- For evalDialect -->
	<xs:simpleType name="eval">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SQL" />
			<xs:enumeration value="REGEX" />
			<xs:enumeration value="BASIC" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="policyResponseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="policyDefinedFact" />
			<xs:enumeration value="mappedFact" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== RajaDReactiveWorks/test_git/roi-framework/src/test/resources/Policy-test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<policies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="policies.xsd">
	<policy>
		<!--tES FOR PolicyDefined Fact -->
		<policyName>PolicyDefinedFactTest</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare in (::PS(GetStagingAreas))" />
				<expression name="validPlatformArea" expValue="$platform not in (::PS(GetStagingAreas)) " />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
			
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="Map">
					<factAttribute name="days" type="String">12345</factAttribute>
					<factAttribute name="validoperation" type="List">PCK, REPL,
						RECV, SHIP, DOCK</factAttribute>
					<factAttribute name="restriction">CYC</factAttribute>
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	
	<policy>
	
		<policyName>FactMappingTest</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>false</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$platform  &lt; &gt;  (::PS(GetStagingAreas)) " />
				<evaluateExp>validStageArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="mappedFact">
			<factMapping>(::PS(GetStagingAreas))</factMapping>
		</policyResponse>
		
	</policy>
	
		<policy>
		<!--tES FOR PolicyDefined Map Fact -->
		<policyName>PolicyDefinedFactMapTest</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>false</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare in (::PS(GetStagingAreas))" />
				<expression name="validPlatformArea" expValue="$platform  =  'WOOD' " />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="Map">
					<factAttribute name="days" type="String">12345</factAttribute>
					<factAttribute name="validoperation" type="List">PCK, REPL,
						RECV, SHIP, DOCK</factAttribute>
					<factAttribute name="restriction">CYC</factAttribute>
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	<policy>
		<!--tES FOR PolicyDefined List Fact -->
		<policyName>PolicyDefinedFactListTest</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare in (::PS(GetStagingAreas))" />
				<expression name="validPlatformArea" expValue="$platform  =  'WOOD' " />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
			
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="List">
					<factAttribute name="days" type="String">12345</factAttribute>
					<factAttribute name="validoperation" type="List">PCK, REPL,
						RECV, SHIP, DOCK</factAttribute>
					<factAttribute name="restriction">CYC</factAttribute>
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	
		<policy>
		<!--tES FOR PolicyDefined Fact Attribute String -->
		<policyName>PolicyDefinedFactAttStringTest</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare in (::PS(GetStagingAreas))" />
				<expression name="validPlatformArea" expValue="$platform  =  'WOOD' " />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="List">
					<factAttribute name="days" type="String">12345</factAttribute>
					<factAttribute name="time" type="Long">78799</factAttribute>
					
					<factAttribute name="validoperation" type="List">PCK, REPL,
						RECV, SHIP, DOCK</factAttribute>
					<factAttribute name="restriction">CYC</factAttribute>
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	
	
	
		<policy>
		<!--tES FOR PolicyDefined Fact Attribute Primitive-->
		<policyName>PolicyDefinedFactAttPrimitiveTest</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare in (::PS(GetStagingAreas))" />
				<expression name="validPlatformArea" expValue="$platform  =  'WOOD' " />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="Map">
				   <factAttribute name="days" type="Integer">34</factAttribute>
					<factAttribute name="day" type="Boolean">false</factAttribute>
					<factAttribute name="seconds" type="Long">78799</factAttribute>
					<factAttribute name="price" type="Double">34.56</factAttribute>
					<factAttribute name="amount" type="Float">34.5</factAttribute>
					<factAttribute name="validoperation" type="List">PCK, REPL,
						RECV, SHIP, DOCK</factAttribute>
					<factAttribute name="restriction">CYC</factAttribute>
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	
	
	<policy>
		<!--tES FOR PolicyDefined Fact Attribute Primitive-->
		<policyName>PolicyDefinedFactAttDateTest</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare in (::PS(GetStagingAreas))" />
				<expression name="validPlatformArea" expValue="$platform  =  'WOOD' " />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="Map">
				   <factAttribute name="date" type="Date">12/14/2015</factAttribute>
					
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	
		
	
		<policy>
		<!--tES FOR PolicyDefined Fact Attribute Primitive-->
		<policyName>PolicyDefinedFactAttDateTestOne</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare != (::PS(GetStagingAreas))" />
				<expression name="validPlatformArea" expValue="$platform = 'wood'" />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="Map">
				   <factAttribute name="date" type="Date">12/14/2015</factAttribute>
					
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	
		<policy>
		<!--tES FOR PolicyDefined Fact Attribute Primitive-->
		<policyName>PolicyDefinedFactAttDateTestTwo</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare is NULL" />
				<expression name="validPlatformArea" expValue="$platform iS NOT NULL" />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
			<policyDefinedFact>
				<factDescription type="Map">
				   <factAttribute name="date" type="Date">12/14/2015</factAttribute>
					
				</factDescription>
			</policyDefinedFact>
		</policyResponse>
		
	</policy>
	
	
	
		
	
	<policy>
		<!--tES FOR PolicyDefined Fact Attribute Primitive-->
		<policyName>PolicyDefinedFactAttDateTestThree</policyName>
		<feature featureGroup="featuregroup1" featureName="feature1" vendor="" />
		<enabled>true</enabled>
		<fact>
			<name>ValidAreas</name>
			<type>com.getusroi.inventory.bean.PicArea</type>
		</fact>
		<policyEvaluation>
			<evaluation evalDialect="SQL" salience="1">
				<expression name="validStageArea" expValue="$dstare &gt; (::PS(platform)) " />
				<expression name="validPlatformArea" expValue="$platform &lt;  (::PS(dstare))" />
				<evaluateExp>validStageArea AND validPlatformArea</evaluateExp>
			</evaluation>
		</policyEvaluation>
		
		<policyResponse type="policyDefinedFact">
